// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI_wCwtBWJtMFrpZvQvviDbMKj3katnVw',
    appId: '1:724450359732:web:6c0edfb92bd7d924d6dae1',
    messagingSenderId: '724450359732',
    projectId: 'testnote-mvp',
    authDomain: 'testnote-mvp.firebaseapp.com',
    storageBucket: 'testnote-mvp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOuTJKyTk9fEQ2cqhkvp1ICAv-CjygLWc',
    appId: '1:724450359732:android:c843381f8f545678d6dae1',
    messagingSenderId: '724450359732',
    projectId: 'testnote-mvp',
    storageBucket: 'testnote-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDncS6GWtPH9a9gjbQpDzRqtJDggaFlq8E',
    appId: '1:724450359732:ios:b01df3e5a6cd19e2d6dae1',
    messagingSenderId: '724450359732',
    projectId: 'testnote-mvp',
    storageBucket: 'testnote-mvp.firebasestorage.app',
    iosBundleId: 'com.example.testnoteMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDncS6GWtPH9a9gjbQpDzRqtJDggaFlq8E',
    appId: '1:724450359732:ios:b01df3e5a6cd19e2d6dae1',
    messagingSenderId: '724450359732',
    projectId: 'testnote-mvp',
    storageBucket: 'testnote-mvp.firebasestorage.app',
    iosBundleId: 'com.example.testnoteMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI_wCwtBWJtMFrpZvQvviDbMKj3katnVw',
    appId: '1:724450359732:web:e29f6ec003dc2b6fd6dae1',
    messagingSenderId: '724450359732',
    projectId: 'testnote-mvp',
    authDomain: 'testnote-mvp.firebaseapp.com',
    storageBucket: 'testnote-mvp.firebasestorage.app',
  );

}